### ISSUE TITLE
tslint.yaml is ignored

### ISSUE THREAD

**Issue by nevercast** [google/gts#173]
https://github.com/google/ts-style/blob/master/src/lint.ts#L63-L66

It seems gts does not look for a yaml file and will jump to using the gts default. ts-lint supports yaml as a config file, it would be nice if gts would try load that too.

**Comment by ofrobots** [comment]
:+1: sounds reasonable. Contributions are always welcome 😃.

**Comment by JustinBeckwith** [comment]
In the latest version, we're moving to `eslint`, which does try to use the local eslint file if provided.  So good news there :)
