### ISSUE TITLE
Document recommended auto-fix-on-save configuration for Visual Studio Code

### ISSUE THREAD

**Issue by carnesen** [google/gts#210]
As a developer, I expect to be able automatically fix most lint+format errors on "save" in my editor. [And it's not just me](https://github.com/prettier/prettier/issues/4327#issuecomment-400510237). (That's a Googler!) We should document how to achieve that with `gts` and Visual Studio Code (vscode), a very (if not the most) popular IDE among TypeScript developers. It took me several hours, but I finally figured out the "secret sauce" to make this happen. It involves two extensions whose configurations must be finely tuned to avoid things like https://github.com/Microsoft/vscode-tslint/issues/294 .

**Comment by ofrobots** [comment]
@carnesen would you be willing to open a PR for this? That would be awesome.

**Comment by carnesen** [comment]
@ofrobots The instructions will change after the clang-format --> prettier cutover so probably best to wait for that. I'd have to recreate the secret sauce anyway; I lost my VS Code settings when my laptop died :`(
