### ISSUE TITLE
`gts fix` should tell the user what files it fixed

### ISSUE THREAD

**Issue by carnesen** [google/gts#211]
Currently the `gts fix` command has no console output on success. It should provide feedback to the user at least as to what files it modified.

Note: I'm filing this mostly to help make my case for a switch to Prettier in https://github.com/googleapis/google-cloud-node/issues/2842 . I'll be adding a comment there soon that references this issue. If we switch to tslint + prettier (via tslint-plugin-prettier), this issue will be fixed for free.

**Comment by JustinBeckwith** [comment]
On master and in 2.0, we're shelling out to eslint/prettier - so you're going to get this by default :)
