### ISSUE TITLE
Console output of "gts fix --dry-run" should be consistent with output of "gts fix"

### ISSUE THREAD

**Issue by carnesen** [google/gts#212]
Currently the console output of `gts fix --dry-run` is similar (but not identical) to the output of `gts check`. (Just FYI the difference is that it if there are both tslint and clang diffs, only the former get reported by `fix --dry-run`.) Instead the output of `gts fix --dry-run` should be identical to what would be output by `gts fix`.

Note: I'm filing this mostly to help make my case for a switch to Prettier in googleapis/google-cloud-node#2842 . I'll be adding a comment there soon that references this issue. If we switch to tslint + prettier (via tslint-plugin-prettier and tslint-config-prettier), this issue will be fixed "for free".

**Comment by JustinBeckwith** [comment]
With the code on master and in 2.x (not released yet), we've moved to using the `eslint` executable under the hood of `gts`.  The `--dry-run` option is now directly mapped to `eslint --fix-dry-run`, so the output is identical :)

We're also on prettier now too!
