### ISSUE TITLE
Should we be banning `.skip`?

### ISSUE THREAD

**Issue by JustinBeckwith** [google/gts#269]
I don't know the right answer here, but I wanted to start a discussion :)  On master, using `.skip` on `mocha` tests is not allowed without an exclusion.  

What's the general guidance here supposed to be?  As someone managing code bases with `.skip` in it from time to time are we saying you should:
1. Just use an exclusion rule?
1. Just delete the skipped test and file a bug?
1. Comment it out and leave it sitting around?

My instincts say to delete the skipped test and file a bug - but I wanted to hear what other's guidance was :)

**Comment by JustinBeckwith** [comment]
cc @google/google-node-team

**Comment by ofrobots** [comment]
A `.skip` implies that a test needs work, but we are not ready to finish that work just yet. This sounds like a job for an issue tracker rather than disabled or commented code.

**Comment by JustinBeckwith** [comment]
SGTM :)
