### ISSUE TITLE
`npx gts init` command does not install gts

### ISSUE THREAD

**Issue by dan1wang** [google/gts#278]
I followed the instruction on the top page (run `npx gts init`) but kept getting error when I open my .ts file on Atom. I finally resolved the problem by executing `npm install gts` in my project directory.

A probable cause may be that my project directory only has a "src" sub-directory and nothing else (no "node_modules" sub-directory or "package.json" file. Please investigate if this is an issue and fix the code.

**Comment by ofrobots** [comment]
Hi @dan1wang.

I tried to reproduce using the following workflow:

1. Create empty directory: `test/`.
1. Create a subdirectory `test/src` and add an `index.ts` file there.
1. Run `npx gts init` in the `test/` directory.

At this point I see a `gts` generate a `tsconfig.json`, a`package.json` and the rest. It also install `gts`, `typescript` and other dependencies locally.

In other words, I cannot reproduce a problem. If you can provide more detailed instructions on how to reproduce the scenario where you saw a problem, we'll be happy to take a look.

**Comment by dan1wang** [comment]
I tried again, and same thing. If I run `npx gts init`, I get `package.json`, `tsconfig.json`, `tslint.json`, and `.clang-format` but no `gts` directory.

```
package.json does not exist.
? Generate Yes
Writing package.json...
{ scripts:
   { test: 'echo "Error: no test specified" && exit 1',
     check: 'gts check',
     clean: 'gts clean',
     compile: 'tsc -p .',
     fix: 'gts fix',
     prepare: 'npm run compile',
     pretest: 'npm run compile',
     posttest: 'npm run check' },
  devDependencies: { gts: '^0.9.0', typescript: '~3.1.0' } }
Writing ./tsconfig.json...
{
  "extends": "./node_modules/gts/tsconfig-google.json",
  "compilerOptions": {
    "rootDir": ".",
    "outDir": "build"
  },
  "include": [
    "src/*.ts",
    "src/**/*.ts",
    "test/*.ts",
    "test/**/*.ts"
  ]
}

Writing ./tslint.json...
{
  "extends": "gts/tslint.json"
}

Writing ./.clang-format...
Language:        JavaScript
BasedOnStyle:    Google
ColumnLimit:     80
```

If I run `npm install gts`, all the dependencies are installed:
```
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\xyz\Desktop\test\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\xyz\Desktop\test\package.json'
npm WARN gts@0.9.0 requires a peer of typescript@^2.7.1 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint@5.13.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >=3.0.0-dev || >= 3.1.0-dev || >= 3.2.0-dev but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@2.29.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >= 3.0.0-dev || >= 3.1.0-dev but none is installed. You must install peer dependencies yourself.
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

+ gts@0.9.0
added 181 packages from 85 contributors and audited 307 packages in 19.126s
found 0 vulnerabilities
```

**Comment by ofrobots** [comment]
Here's the code: https://github.com/google/gts/blob/2be7ac9fb291502f632833abf37e531e3ade3e5b/src/init.ts#L284-L293

In other words, `init` **will** spawn an `npm install` automatically unless you pass `--dry-run`. Is there any chance you are using an attenuated or custom node binary that has the `child_process` (e.g. spawnSync) module removed?

Can you provide the full version output from Node.js (`node -p process.versions`) and the version of npm you have (`npx --version`).

With that said, I haven't never heard of this problem reported before, and given the code above, I can see no obvious reason why it doesn't work for you. I would likely need a way to reproduce this to be able to solve this problem.

**Comment by dan1wang** [comment]
Here's `node -p process.versions`
```
{ http_parser: '2.8.0',
  node: '10.15.0',
  v8: '6.8.275.32-node.45',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
```
and npx version is 6.4.1

How can I run `npx gtx init` without `--dry-run`?

**Comment by ofrobots** [comment]
Dry-run applies only when it is explicitly passed in. As long as you are not passing the `--dry-run` flag, you're good.

I have tried with the exact same node and npx versions you mention, but I still cannot reproduce this problem. Without a repro, and nothing obviously wrong in the code, I am not sure I can debug this on my end.

If you want you can add some console.log statements to your copy of `build/src/init.js` and see if you can figure out what is wrong?

**Comment by dan1wang** [comment]
Found the problem. I am on Windows, and I apparently you need to append ".cmd" after "npm" for install to work.

**Comment by arvindkhadri** [comment]
Hi. I tried using `gts` today on MacOS. I ran `npx gts init`, but `gts` was not installed, only config files got modified. This was with gts@2.0.0. I had to run `npm install gts` to run `gts fix` etc.
