### ISSUE TITLE
Confusion around what prettier format configuration is used

### ISSUE THREAD

**Issue by leeren** [google/gts#279]
I like to separate formatting and linting separately. The output from running `$(npm bin)/gts fix file.ts` and `prettier file.ts --write` are completely different, though, even if I specify using the `prettier.config.js` file included in `gts`. 

Where exactly are the gts-style prettier formatting settings specified?  Also, is there a better way of separating out formatting and linting?

**Comment by ofrobots** [comment]
Hi @leeren. Our `master` branch is working towards using `prettier` for formatting, but the latest released version of module on npm still uses clang-format. You can try out the upcoming 1.0 release by installing from master `npm i google/gts`. Sorry for the confusion.

> Also, is there a better way of separating out formatting and linting?

What would be the cases where you want to to fix the formatting but not the auto-fixable linting errors? If there are reasonable use-cases here, it may make sense to add an additional `format` verb.

**Comment by leeren** [comment]
@ofrobots ah, that explains everything! What's the expected release date of 1.0? 

> What would be the cases where you want to to fix the formatting but not the auto-fixable linting errors? If there are reasonable use-cases here, it may make sense to add an additional `format` verb.

The use-case is if I want to preview the formatting / linting errors and be able to disambiguate between the two. I know `gts check` already does this by first listing linting errors and then formatting ones. The preference is more geared towards being able to integrate the error checks into compilers of editors. I should have reworded my concern:

It would be great if, for example, `gts check` could be configured to output errors in a compiler-friendly format. For linting, this would be as simple as allowing the option for `tslint` to use the default formatter (`-t prose`).  An editor's compiler can then integrate with this using an error-recognition pattern like `%EERROR:\ %f:%l:%c\ -\ %m`. For formatting, this would also be nice but I don't think `prettier` supports compiler-friendly error checking.
