### ISSUE TITLE
What's about yarn?

### ISSUE THREAD

**Issue by vitkarpov** [google/gts#281]
Hey there!

Thanks for this project. I'm wondering would it be useful to allow `gts` using yarn instead of npm while init?

Why did I pay attention to it? I use yarn across my projects and for a new project I created package.json first (using `yarn init`), added `gts` as a dev dependency and run `npx gts init`. What I got was package-lock.json near yarn.lock 🤔  

They have pretty much the same API, so I just changed [npm here](https://github.com/google/gts/blob/master/src/init.ts#L295) to yarn and that's it. I'd suggest to automatically look at "is there `yarn.lock` or not" and switch between them (not only for init but everywhere, probably an adaptor needs to be introduced so it's not a trivia)

What do you, fellows, think about it? Probably, there's a reason to use `npm` only?

**Comment by ofrobots** [comment]
Hi @vitkarpov . We defaulted to `npm` because most people will have that. Yarn probably has enough usage that merits being supported too. The logic you propose sounds reasonable. Do you want to submit a PR 😀?

**Comment by vitkarpov** [comment]
👆 yep, I'd love to because I'm using `gts` now and kind of interested in its development 😃 I'll poke around the code first and probably get back with questions then.

**Comment by vitkarpov** [comment]
@ofrobots let's discuss the API, I'd suggest:

```diff
...
   Options
     --help        Prints this help message.
     -y, --yes     Assume a yes answer for every prompt.
     -n, --no      Assume a no answer for every prompt.
     --dry-run     Don't make any acutal changes.
+    --yarn, -r    Use yarn instead of npm (the latter by default).
...
```

WDYT?

**Comment by ofrobots** [comment]
I would suggest eschewing the short form `-r`, and just keep the long form. IMO `-r` is not memorable, and `--yarn` is not too much longer to type.

I am guessing that the logic would be:

- If only `yarn.lock` exists, use `yarn`.
- If only `package-lock.json` exists, use `npm`.
- If neither or both exist, use `npm` unless the `--yarn` flag was passed.

**Comment by vitkarpov** [comment]
Perfect! 🙇I'll proceed in that direction then.

**Comment by vitkarpov** [comment]
@ofrobots made a PR, please, take a look when you have some time. Thanks!
