### ISSUE TITLE
e2e tests

### ISSUE THREAD

**Issue by vitkarpov** [google/gts#287]
Ladies and gentleman! 👋 🍷 

While doing https://github.com/google/gts/pull/285, I noticed that there are no e2e tests. I mean, surely we have tests for `init` with different configs but it'd be robust to have full e2e tests (call CLI using `execa` and assert output, filesystem and so on), right?

In my case, I checked that `yarn` is used if there's `yarn.lock` indeed only manually (there's a unit test though but anyway).

What do you think if someone (me) brings those kind of tests here?

**Comment by ofrobots** [comment]
Hi @vitkarpov. [test-kitchen.ts](https://github.com/google/gts/blob/master/test/test-kitchen.ts) is supposed to be the end-to-end test. It is not as extensive as one could want, but it is there. It would be awesome if you want to expand the e2e tests here ❤.

**Comment by vitkarpov** [comment]
> test-kitchen.ts is supposed to be the end-to-end test.

Ah, I see that now, thanks! 👍
