### ISSUE TITLE
Trailing commas

### ISSUE THREAD

**Issue by sk-** [google/gts#292]
The tslint config should ask for trailing commas in objects and 
 arrays. That would be in sync with what is asked in the JS styleguide https://google.github.io/styleguide/jsguide.html#features-objects-use-trailing-comma. AFAIK the TS styleguide hasn't been published yet.

You can use the following config to achieve this:
```json
"trailing-comma": [
  true,
  {
    "multiline": {
      "objects": "always",
      "arrays": "always",
      "functions": "never",
      "typeLiterals": "ignore"
    },
    "esSpecCompliant": true
  }
]
```

see the [docs](https://palantir.github.io/tslint/rules/trailing-comma/).

**Comment by ofrobots** [comment]
AFAICT, trailing-commas aren't a requirement in the (not yet public) TS style guide. Looking at the copy of `tslint.conf` used internally at Google, I don't see the `trailing-comma` rule either. Based on that my assumption is that this is not required by the Google TS Style Guide. /cc @mprobst if this is incorrect or if there is anything to add about the rationale here.

**Comment by mprobst** [comment]
TS style doesn't mandate currently, but maybe we should. It's in a bit of a
half-state, where clang-format does one-per-line formatting if you have a
trailing comma, and per-line of not, unless you exceed 80 cols. I think in
practice people use trailing commas for multiline container literals, and
that's probably a good idea.

**Comment by ofrobots** [comment]
I agree that it is a good idea. Given that this would be semver major for the tool here, I am going to pull this one in for the upcoming `1.0`.
