### ISSUE TITLE
TS18003: No inputs were found in config file

### ISSUE THREAD

**Issue by pliski** [google/gts#312]
### Problem
tsc doesn't find anything to compile in the directories included in tsconfig.json.

### Repro steps

-  ```npx gts init```

- ```npm i```

### Workarounds

- delete the **prepare** script in package.json (this will prevent to compile on npm i)

OR

-  ```mkdir src && touch src/dummy.ts```

### Final thoughts
This behavior does not appear friendly to the user, better approach will be to include some dummy code to avoid the error.
Even better will be to generate some template code to get the new project up and running from the beginning and assure that everything is installed correctly.

### Proposition
- init.ts : new  function generateTemplateCode() will create src dir and an example index.ts,
- init.ts : modify function init() to call also generateTemplateCode(),
- package.json: create a **run** script that will compile and execute the template project.

**Comment by ofrobots** [comment]
@pliski your proposal sounds good. Want to sent a PR? :)

**Comment by pliski** [comment]
ok. I'll have some time later today.
