### ISSUE TITLE
gts 1.0.0 logging errors unnecessarily?

### ISSUE THREAD

**Issue by callmehiphop** [google/gts#326]
Not actually sure if this is a bug, but I found the behavior confusing. Using 1.0.0 if I run `gts fix` it will report errors that I would think are fixable via `gts`. Interestingly enough it appears that these issues do get fixed as any subsequent runs no longer report said errors.

Here's some (probably unhelpful) output

```
/Users/taco/projects/nodejs-pubsub/src/iam.ts
Missing semicolon (semicolon)
  43 |  */
  44 | export interface IamPermissionsMap {
> 45 |   [key: string]: boolean
     |                        ^
  46 | }
```

**Comment by JustinBeckwith** [comment]
I know this sounds lame, but I've been able to fix these by running `gts fix` twice 🐒

**Comment by callmehiphop** [comment]
@JustinBeckwith yeah, that is what I've been doing. Just figured I'd open an issue to get it on the radar

**Comment by ofrobots** [comment]
Anyone have a repo? I would like to experience this for myself as well. Maybe we can internally iterate until we reach a fixed point?

**Comment by callmehiphop** [comment]
@ofrobots I've really only noticed it happen for missing semicolons on types like the one in my description.
