### ISSUE TITLE
Explore using CirrusCI

### ISSUE THREAD

**Issue by JustinBeckwith** [google/gts#331]
I noticed in a recent commit that we were playing with Windows support, and using Kokoro to do that.  While Kokoro is great for some things, it may be worth exploring Cirrus:
https://cirrus-ci.org/

I've been using this for personal projects, and I've been very happy.  Here's an example config:
https://github.com/JustinBeckwith/linkinator/blob/master/.cirrus.yml

They seem to support windows out of the box:
https://cirrus-ci.org/guide/windows/

I'd be happy to take a shot at this if others think it's a good idea.  Also happy to just stick with Kokoro if that's what folks want :)

**Comment by ofrobots** [comment]
I think it would be worth while setting it up and seeing how whether it ends up being more productive than kokoro to run/view/debug. 👍

**Comment by JustinBeckwith** [comment]
We are actively exploring :)
