### ISSUE TITLE
Lint/check ignores local prettier.config.js config 

### ISSUE THREAD

**Issue by dim** [google/gts#347]
This leads to inconsistencies between with `gts fix`, for example:

```shell
$ cat prettier.config.js 
module.exports = {
  singleQuote: true,
  trailingComma: 'all',
};

$ node_modules/.bin/gts fix file.ts
Warning: The 'deprecation' rule requires type information.
Done in 2.06s.

$ node_modules/.bin/gts check file.ts
file.ts
Unnecessary trailing comma (trailing-comma)
  44 |     input: string,
  45 |     replacement: string,
> 46 |     count: number,
     |                                   ^
  47 |   ): string {
  48 |     if (replacement == null) return input;
```

**Comment by guoyr** [comment]
Same problem. Since gts copies `prettier.config.js` to the repo root, it should use that, instead of the one in its own repo: https://github.com/google/gts/blob/4a3c51143856b462804b318a5fce6baa2784e549/src/format.ts#L24

**Comment by ofrobots** [comment]
Thanks for reporting the issue, we'll take a look.

**Comment by ofrobots** [comment]
@guoyr @dim: I am unable to reproduce this. Can you provide a more complete repro? Note that we use the default gts config if we cannot find a config provided by the user.  We use prettier's `resolveConfig` on a per-file basis to get this done:

https://github.com/google/gts/blob/4a3c51143856b462804b318a5fce6baa2784e549/src/format.ts#L63-L65

Here's a existing test case that verifies that user provided config is used:
https://github.com/google/gts/blob/4a3c51143856b462804b318a5fce6baa2784e549/test/test-format.ts#L212-L224

I would really appreciate if you could provide a minimal github repo / gist with a setup that shows the problem.

**Comment by ofrobots** [comment]
Here's another test I created that verifies the trailing comma option works as well:

```ts
  it('format should use user provided prettier.config.js 2', () => {
    return withFixtures({
      'tsconfig.json': JSON.stringify({ files: ['far.ts'] }),
      'prettier.config.js': `module.exports = {
  singleQuote: true,
  trailingComma: 'all',
};`,
      'far.ts': `export function far(
  ceiling: string,
  vines: string,
  sailed: number,
  ocean: number,
  tumbled: string,
): string {
  return 'where the wild things are';
}
`,
    }, async () => {
      const result = await format.format(OPTIONS, [], false);
      assert.strictEqual(result, true);
    });
  });
```

It seems to pass. A reproducing test repo / gist would be needed to investigate this further.

**Comment by dim** [comment]
The formatting is fine, it's the check that's not taking into account the
local configuration

**Comment by dim** [comment]
Please take another look at my example in the original report. `gts fix file.ts` terminates without changes, while `gts check file.ts` reports errors.

**Comment by guoyr** [comment]
Alas I could not repro this problem in a new node project. Sorry for the false alarm! Thanks for pointing out `resolveConfig()`.

**Comment by dim** [comment]
@ofrobots here's an example repo: https://gist.github.com/dim/4415b82946149f8823c8a1b77108b7d4

```
$ yarn gts fix
yarn run v1.16.0
$ ./node_modules/.bin/gts fix
Done in 1.76s.
$ yarn gts check
yarn run v1.16.0
$ ./node_modules/.bin/gts check
./file.ts
Unnecessary trailing comma (trailing-comma)
  1 | export function sum(
  2 |   forSomeReasonThisIsAVeryLongVariableName1: number,
> 3 |   forSomeReasonThisIsAVeryLongVariableName2: number,
    |                                                   ^
  4 | ): number {
  5 |   return (
  6 |     forSomeReasonThisIsAVeryLongVariableName1 +


error Command failed with exit code 1.
```

**Comment by ofrobots** [comment]
So here's what's going on, given the config you have provided:

* `tslint` does not allow unnecessary trailing commas, but `prettier` config allows it.
* `gts fix` runs `lint` first then `prettier`. `tslint` removes the command, `prettier` adds it back in.

**Comment by ofrobots** [comment]
The solutions seems to be using something like [tslint-config-prettier](https://github.com/prettier/tslint-config-prettier). It removes conflicting style rules from the `tslint` config.
