### ISSUE TITLE
Use the `no-unused-variable` rule 

### ISSUE THREAD

**Issue by JustinBeckwith** [google/gts#351]
We noticed a few dead imports lying around in a PR, and thought it could be useful to tighten that kind of thing up with the linter.  Would be rad to add this rule to the default config:
https://palantir.github.io/tslint/rules/no-unused-variable/

**Comment by ofrobots** [comment]
👍. Note that this would be semver major, so it will take a little bit of time before we release it. Perhaps we can bundle this with the migration to eslint?

**Comment by JustinBeckwith** [comment]
This is fixed on master already!  The default `eslint:reccomended` config brings in the `no-unused-labels` rule, which fixes this.
