### ISSUE TITLE
Import the rules to SonarQube

### ISSUE THREAD

**Issue by guoyongchina** [google/gts#366]
Can we export the Typescript rules from gts,   add import the rules to SonarQube?

**Comment by JustinBeckwith** [comment]
Greetings!  This library is now based on eslint.  If eslint rules can be imported, then this can be imported :)  At a glance - it looks like SonarQube is GPL licensed, and written in Java:
https://github.com/SonarSource/sonarqube

Given both of those constraints... I don't think this will be reasonable to do any time soon.  Apologies!
