### ISSUE TITLE
Need option for specifying --project

### ISSUE THREAD

**Issue by robert-e-davidson3** [google/gts#372]
The `deprecation` rule is not being run because type checking is not enabled. In tslint, it's enabled via the CLI by specifying a project (the `tslint.json` file). This shortcoming also applies to other useful rules like `no-floating-promises`.

Unfortunately tslint does not accept `project` as an option. It's purely part of the tslint CLI. I tried coming up with a reasonable solution but I don't know tslint very well so I couldn't figure out how TypedRules work. My hope is that someone here has a much better idea.

**Comment by JustinBeckwith** [comment]
With the code on master and in the upcoming 2.x release, we've switched over to eslint.  This means you should be able to use any other eslint plugins you'd like :)
