### ISSUE TITLE
gts does not respect .prettierignore 

### ISSUE THREAD

**Issue by ILMTitan** [google/gts#375]
Prettier can [ignore files](https://prettier.io/docs/en/ignore.html) with a .prettierignore file. The entrypoint to prettier used by gts, however, does not support that option.

**Comment by JustinBeckwith** [comment]
On master and in 2.0 we're shelling out to eslint - so this is going to work by default now :)  Please give master a whirl and let us know if it's still causing issues!

**Comment by hawkinsw** [comment]
I am sorry to reopen this, but I was wondering two quick things:
1. Is there a workaround in the meantime? 
2. How long until 2.0 is released? I played with the alpha release and had nothing but trouble. 

I know that you are all working on this as diligently as possible and I appreciate your great tool! Thanks for everything that you are doing!
