### ISSUE TITLE
gts check: “Warning: The 'deprecation' rule requires type information.”

### ISSUE THREAD

**Issue by jeff00seattle** [google/gts#376]
When performing `gts check` it shows the following Warning and I am not sure how to resolve it:
**`Warning: The 'deprecation' rule requires type information.`**

Typescript files are found in the following directory:
```
$ find ./src -type f -name "*.ts"
./src/metrics/index.ts
./src/metrics/events/index.ts
./src/utils/api-client.ts
./src/archives/ArchiveManager.ts
./src/archives/index.ts
```

In **`project.json`** script were declared here:

```
"scripts": {
  "code:check": "gts check src/archives/*.ts",
}
```

`npm run code:check` returns said `Warning`.

**Comment by JustinBeckwith** [comment]
This was a bug specific to tslint being unable to pass a --project flag when being invoked.  In the 2.x release on master (not published yet), we've moved over to eslint so this shouldn't be a problem :) Please do let us know if you're still seeing this when running against master!
