### ISSUE TITLE
TypeScript 3.7 support

### ISSUE THREAD

**Issue by bhollosi** [google/gts#386]
New language features (such as Optional Chaining, Nullish Coalescing..) fails with `SyntaxError: Expression expected` message.

**Comment by bhollosi** [comment]
Related to https://github.com/prettier/prettier/issues/6595 .
gts@master with prettier@master is work like a charm on a TS 3.7 project!

**Comment by JustinBeckwith** [comment]
Pretty sure we got this figured out :)
