### ISSUE TITLE
Should there be allowance for pascal casing in required modules?

### ISSUE THREAD

**Issue by autotel** [google/gts#409]
# context

This might or might not be an issue. It is very likely that I am missing the right way to do it. I did a bit of research, but this issue is so specific that it was hard to find anything. 

I am working with es6 interoperability, because I need to import some libraries written in javaScript. I thought it would be best to express this by importing the module by using `const MyClass=require("my-library")` instead of `import * as MyClass from 'my-library'`. Of course that the library exports by default only the `MyClass` class. As you can see the typescript way of doing it is a bit awkward. It has to be noted that I am writing the definition files myself.

# problem
The problem that I ran into, is with that javaScript style of import. It raises an issue because the MyClass variable name is pascal case (since I am going to instance it), however, the linter detects that as a variable with wrong casing.

# possible solutions
these are the ones I can imagine; either:

* It is my bad, because there is a way to indicate the linter that this variable is a class.
* It is my bad because I am obliged to always import the typescript way, even if the library is javaScript
* There is a feature to be added to this linter, where pascal casing is allowed when importing a library whose default import is a class.

# the code in my case
@types/audio-biquad.d.ts
```
declare interface myParamsInterface{
    type:"bandpass"|"lowpass"|"highpass",
    frequency: number,
    Q: number,
    gain: number,
}

declare module 'audio-biquad'
{
    class AudioBiquad {
        constructor(params:myParamsInterface);
        process(buffer:any);
    }
    export = AudioBiquad;
}
```
any file that uses "audio-biquad"
```
const AudioBiquad = require('audio-biquad');
```

**Comment by autotel** [comment]
I realized I was actually not running with the `esModuleInteroperability` flag. For anyone looking for solution to this in the future; this is how I declared and imported an es module that exports just a class:

audio-biquad.d.ts
```
declare module 'audio-biquad' {
    interface myParamsInterface{
        type:"bandpass"|"lowpass"|"highpass",
        frequency: number,
        Q: number,
        gain: number,
    }
    class Biquad {
        constructor(params:myParamsInterface);
        process(buffer:any);
    }
    export=Biquad;
}
```

it is imported like:
```
import Biquad from 'audio-biquad';
```
 
I don't know if gts allows by rule using "require" as a way of importing. If it is allowed, it would still be meaningful that the variable name which contains the class was allowed to be named with pascal case.

**Comment by JustinBeckwith** [comment]
Good to hear that this got worked out!  Now that the library is based on eslint, you can manually twiddle with the `camelcase` rule:
https://eslint.org/docs/rules/camelcase

If you ended up in this position again, you can disable the rule :)
