### ISSUE TITLE
Extending config requires `./node_modules/gts` path

### ISSUE THREAD

**Issue by JustinBeckwith** [google/gts#429]
With eslint, we're supposed to be able to export a config from a shared module (this one), and import it just with the module name (`gts`):
https://eslint.org/docs/developer-guide/shareable-configs

For some reason, I'm having trouble getting this to work, and instead of this:
```js
{
    "extends": "gts"
}
```

I need to write it as this:
```js
{
    "extends": "./node_modules/gts"
}
```

**Comment by JustinBeckwith** [comment]
So I dug deeper into the machinery of eslint configs.  If the package name doesn't start with `eslint-config-`, the naked extend simply won't work 😕 

For now, this one is WAI.

**Comment by oxc** [comment]
Have you considered publishing the eslint config as a separate package (which could have this prefix)? This would also help projects that are interested in including the config without the rest of gts.
