### ISSUE TITLE
check run script conflicts with yarn check

### ISSUE THREAD

**Issue by darkbasic** [google/gts#449]
See https://yarnpkg.com/en/docs/cli/check

yarn has a shorthand version for `yarn run <script>`: `yarn <script>`
Most yarn users are used to it and forget about using `yarn run`, but unfortunately yarn already has a deprecated `check` command which gets prioritized.

Proposed solution: rename the check script to `inspect`

**Comment by Maxim-Mazurok** [comment]
I don't like `inspect`...
