### ISSUE TITLE
variable-name removed in gts@2.0.0

### ISSUE THREAD

**Issue by zamnuts** [google/gts#486]
TSLint's `variable-name` rule existed in `gts@1`:

https://github.com/google/gts/blob/4f211518984bd09a346624f86167c4da965627b5/tslint-rules.json#L70-L76

Per [typescript-eslint's ROADMAP style section](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md#style) (migration guide?), the TSLint `variable-name` equivalent is now `@typescript/naming-convention`. See [rules/naming-convention](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md).

Since `variable-name` was removed and `naming-convention` was not included, variable name linting is now more relaxed, i.e. a possible regression.

While the new `naming-convention` allows for significantly more control, a 1:1 replacement would be:
```
---
rules:
  '@typescript-eslint/naming-convention':
    - error
    - selector: variable
      format: ['camelCase', 'UPPER_CASE']
      leadingUnderscore: allow
      trailingUnderscore: allow
      custom:
        regex: 'any|[Nn]umber|[Ss]tring|[Bb]oolean|[Uu]ndefined'
        match: false
```

`naming-convention` does not explicitly include support for the `ban-keywords` option, so `custom` with a regex was included above to provide equivalency. See https://github.com/palantir/tslint/blob/8efa78e35a88b62775ce3c9bf0fa00586b0d34e1/src/rules/variableNameRule.ts#L26-L36

**Comment by JustinBeckwith** [comment]
We ultimately decided to let this one go
