### ISSUE TITLE
gts check checks on the build folder

### ISSUE THREAD

**Issue by ItsRauf** [google/gts#497]
Running `gts check` checks files in the build folder

**Steps to reproduce the behavior**
1. Install gts `npx gts init`
2. Write some source code
3. Compile it using `npm run compile`
4. Check it using `npm run check`

**Expected behavior**
It checks only the source typescript files

**Actual Behaviour**
It includes the build folder too.

**Screenshot**
![image](https://user-images.githubusercontent.com/31735267/80856872-aa74ac00-8c1b-11ea-9715-3d9e6418235e.png)

**Additional context**
gts version: 2.0.0
node version: 12.14.1

`C:\Users\Rauf\code\lifeguardv3\bot` is the base directory of the project where gts was initialized in

**Comment by ItsRauf** [comment]
one possible temporary solution is to use ` npm run check 'src/**/*.ts'`

**Comment by dotdoom** [comment]
Looks like a dup of #483.

**Comment by ItsRauf** [comment]
whoops, didnt see that when looking to see if this issue was reported, will close this one then.
