### ISSUE TITLE
Q: Why build/src

### ISSUE THREAD

**Issue by naseemkullah** [google/gts#519]
Hello I noticed since gts 2.x.x, compipled files go in `build/src` rather than `build/` directly, i think it may have something to do with having test folder at same level as src folder, but could you kindly elaborate on the reasoning? `build/src` seems a little weird but then again there does not seem to be any convention around dir structure

**Comment by JustinBeckwith** [comment]
There are a few things to separate here :) `gts init` is opinionated, and will generally set up things the way we do TypeScript on the Google Cloud team. For us, that means having top level `src` and `test` directories, and then having the compiled output show up in the `build` directory.  This is consistent between v1 and v2.  

In reality though, you can configure your `tsconfig` any way you like!  If you want to use a different directory structure, and configure your `tsconfig` to do so, `gts` should still work just fine :)

**Comment by naseemkullah** [comment]
Thanks for the quick reply! I was for wtvr reason under the impression that `v1` had a diff default dir structure, guess not!
