### ISSUE TITLE
gts cmd resolves to git tag instead of google-typescript

### ISSUE THREAD

**Issue by PrateekSB** [google/gts#548]
Hi, 

Following the documentation, I ran `npx gts init` which added all necessary files and changes. However, I face the issues while running cmd `gts check` which seems to be resolving to `git tag` (image attached below). 

![image](https://user-images.githubusercontent.com/39911214/90006748-cca9ab80-dc99-11ea-9666-380a3a65d5c8.png)

Also running it any other way leads to the following errors: 

![Screenshot 2020-08-12 at 12 59 07](https://user-images.githubusercontent.com/39911214/90007864-c4eb0680-dc9b-11ea-91dc-d87de60a4843.png)

Please provide a way to resolve as I cannot find documentation or any related issues on that.

Thank and Warm Regards,
Prateek

**Comment by airglow923** [comment]
![image](https://user-images.githubusercontent.com/37762634/95726945-21729e00-0cac-11eb-9a97-847ce9e5d6f5.png)

Also experienced the same problem while using ZSH on WSL 2.

**Comment by airglow923** [comment]
Disabling aliases set by `oh-my-zsh` solved the problem.

You can disable it by appending the following line to `~/.zshrc`:

`unalias -m '*'`

**Comment by airglow923** [comment]
Given that the peoblem relates to `oh-my-zsh`, I think you can close the issue.

**Comment by PrateekSB** [comment]
Hey, thanks for the info!
