### ISSUE TITLE
How about providing a tagged package refers to the head

### ISSUE THREAD

**Issue by pokutuna** [google/gts#554]
Hello, I love this gts project and use this in many projects. This makes me free from chores.

But the release cycles are not so fast beside other typescript ecosystems. I’m always waiting to be released this when new typescript is released. I understand that gts is used in many google typescript projects, but I want to use gts and the latest typescript.

How about providing a tagged package refers to the head of the master? Something like `gts@head` or `gts@beta` are published when CI passed on the master.

As another solution, I can depend on gts as `git+https://github.com/google/gts`, but it doesn't work and I fixed it (#553). But it's better to be provided as a built package.

**Comment by alexander-fenster** [comment]
This looks like a good idea for all our libraries in general, we'll track it in https://github.com/googleapis/repo-automation-bots/issues/4078.
