### ISSUE TITLE
Why does the default tsconfig.ts file have `rootDir: '.'` ?

### ISSUE THREAD

**Issue by tylerlong** [google/gts#573]
```ts
compilerOptions: {rootDir: '.', outDir: 'build'},
```

https://github.com/google/gts/blob/master/src/init.ts#L239

The config file should be minimal. It should not contain configurations which are not necessary.

Every time I run `gts init`, I need to manually remove `rootDir: '.'` because it doesn't make sense to my project.

**Comment by danielbankhead** [comment]
A root directory must be included to TS to work properly, however we're missing the [`composite` flag](https://www.typescriptlang.org/tsconfig/#composite).

We will fix this in this issue:
- https://github.com/google/gts/issues/893
