### ISSUE TITLE
Bug:  await execa without async wrapper

### ISSUE THREAD

**Issue by daxeh** [google/gts#650]
package: [execa](https://www.npmjs.com/package/execa) 
**line 148, 159**

```node
 await execa('node', ['./node_modules/eslint/bin/eslint', ...flags], {stdio: 'inherit',  });
```

it does not seem to be in a valid async/await scope.

**Comment by brunosantanarj** [comment]
Same issue. 
Here the cli frozen on node version.

The solution in the moment for me is change gts commands for `eslint . --ext .ts,.tsx --fix --no-error-on-unmatched-pattern`
