### ISSUE TITLE
Enable more trailing commas, particularly in function parameters and calls

### ISSUE THREAD

**Issue by eefi** [google/gts#662]
I'd like to suggest changing the Prettier trailingComma setting from es5 to all for the next gts release with breaking changes.

https://prettier.io/docs/en/options.html#trailing-commas

In particular, this would enable trailing commas in multiline function parameter lists and calls, which can help reduce commit diff noise.

The Prettier docs note that this requires ES2017 and TypeScript 2.7, but gts already specifies ES2018 and TypeScript 4.x.

**Comment by calebegg** [comment]
+1 to this. The internal prettier config at Google uses `trailingComma: 'all'`
