### ISSUE TITLE
Plans for supporting eslint version 8.x.x

### ISSUE THREAD

**Issue by nouman91** [google/gts#663]
What is the plan for releasing a new version for supporting eslint newer version (8.x.x)

**Comment by nouman91** [comment]
Any update on this?

**Comment by dweisiger** [comment]
also curious about any updates on this, would be awesome to use this

**Comment by stonekyx** [comment]
Looks like gts started to use eslint 8.0.0 from last week? https://github.com/google/gts/commit/7ae5c8b827abb41844ba6f533821bf3d0a7f302b

But there hasn't been a new release for gts for over a year now. Do we have a plan for new release anytime soon?

**Comment by dwinrick-lever** [comment]
Looks like it will go out in: https://github.com/google/gts/pull/684

**Comment by alexander-fenster** [comment]
4.0.0 is out (currently tagged `next` but will become `latest` soon).
