### ISSUE TITLE
Is this being maintained anymore?

### ISSUE THREAD

**Issue by nouman91** [google/gts#664]
Hi,

I see lots of open issues and no response from the maintainers. I just want to know is this lib being maintained anymore?

I am using this in one of the projects and desperately looking for eslint 8.x.x support.

**Comment by mgenereu** [comment]
@bcoe might have some insight. This isn't an official Google product but it would be nice to know if anyone at Google is even interested now that @JustinBeckwith has moved on.  There are several Google npm packages that depend on this as a development dependency and I'm assuming they'll need to update or remove the dependency as well.

Meanwhile for me, I'm locked on TypeScript 4.4.x until this package gets a little love. Modern enough version so I'm hurting too much.

**Comment by bcoe** [comment]
This library is still being supported, we use it for many of my team's own dependencies.

It just isn't currently tracked by my team's dashboards, which help us keep on top of open PRs and issues. I will see about adding it to the dashboard, such that we don't drift behind on triage.

**Comment by mgenereu** [comment]
Thank you so much! Please let us in the community know what we can do to support you in return!

**Comment by ankoor7** [comment]
@bcoe thank you. 

this repo is very very useful!

**Comment by bcoe** [comment]
WE are now tracking issues for this repo, it is most certainly not deprecated.
