### ISSUE TITLE
Indent continuation lines is not enforced?

### ISSUE THREAD

**Issue by saadlu** [google/gts#744]
Google's javascript style insists to have indent of 4 spaces when continuing a line:

https://google.github.io/styleguide/jsguide.html#formatting-indent

How come Google's TypeScript Style (and thereby gts) does not enforce that? Is there no such concept of that in prettier?

**Comment by tonycoco** [comment]
Prettier has stated that there are no more options for us to put in to fix this inconsistency.

https://github.com/prettier/prettier/issues/11897
