### ISSUE TITLE
feat!: Set `no-floating-promises` to `error`

### ISSUE THREAD

**Issue by danielbankhead** [google/gts#793]
Un-revert https://github.com/google/gts/pull/808 and set `no-floating-promises` to `error`

Context:
- https://github.com/google/gts/pull/756#issuecomment-1714363976

Dependency:
- https://github.com/googleapis/synthtool/pull/1877

**Comment by danielbankhead** [comment]
Dependency: https://github.com/googleapis/synthtool/pull/1877

**Comment by naseemkullah** [comment]
hey @danielbankhead can we move forward with this now? I can make a PR if so, thank you!

**Comment by danielbankhead** [comment]
@naseemkullah feel free to create a PR, however it will take some time before we do another major release

**Comment by tonycoco** [comment]
Working on another major release with some changes to drop Node 14/16 soon. Anyone want to create a PR I can help merge.

**Comment by danielbankhead** [comment]
@tonycoco We cannot drop Node 14/16 without a proposal to update all googleapis Node.js client libraries. We're planning to get to this sometime this semester.
