### ISSUE TITLE
Drop support for Node.js 14 and 16

### ISSUE THREAD

**Issue by ozfox** [google/gts#799]
Both of them already reached EOL, v14 in April and v16 just recently on September 11th.

I have come across this because [fix(deps): update typescript-eslint monorepo to v6 (major) #767 ](https://github.com/google/gts/pull/767) was closed, probably because the pipeline for v14 failed. In addition to typescript-eslint, other dependencies have also dropped support or are likely to do so soon.

**Comment by danielbankhead** [comment]
@ozfox unfortunately, our downstream libraries require Node 14+ support. Examples:
- https://github.com/googleapis/nodejs-storage
- https://github.com/googleapis/google-auth-library-nodejs
- https://github.com/googleapis/gaxios

We would love to support Node 18 as minimum, however it will take some time before we make it a minimum.
