### ISSUE TITLE
Discussion: `gts watch`

### ISSUE THREAD

**Issue by JustinBeckwith** [google/gts#81]
As we convert libraries from gulp to gts, the only thing I'm really missing is `npm run watch`.  I'd like to run that command, have it automatically watch for changes in `*.ts*` files or `package.json`, and react by running the 'compile` and `test` commands.  I could see a syntax like this:

`$ gts watch`

By default, it would monitor the sources directory for changes, and run `npm run compile` on change.  We wouldn't let users change it.  After compilation, it would run `npm test`.  On test failure, we would have to be careful to not let the process stop.  

If we want to get fancy - we could support a syntax that runs the start process instead of tests on file change.  This would be useful for web applications where you're more concerned with live development:

`$ gts watch --start`

I'm a little conflicted, because this goes beyond the scope of what we're building - but it is a useful thing I just want to have out of the box with most TypeScript projects.  

Thoughts?

**Comment by ofrobots** [comment]
`tsc --watch` already exists. It doesn't integrate with tests, but perhaps a good starting point. WDYT?

**Comment by JustinBeckwith** [comment]
There are a few things I don't like about `tsc --watch`:
- On file change, I want `npm run compile` to be run, so I don't have to worry about the tsc command being the same in two places. 
- If I'm writing a library, I almost always want the tests afterward
- If I'm working on an app, I almost always want to restart my process, and maybe even reload the web page I'm working on

`tsc --watch` solves a problem in a vacuum, but rarely is actually enough in real life (IMO).

**Comment by carnesen** [comment]
I feel this. I've been finding myself on these `@google-cloud` projects running `tsc --watch` in one shell and `mocha build/test --watch` in another, and I've given up on maintaining lint/format correctness in "real time" as I develop. (Instead I fix once at the end before submitting the PR). I assume here you're asking for a tool that helps to orchestrate those processes. As a linting/formatting tool though, `compile` and `test` are probably outside `gts`s scope.

**Comment by ofrobots** [comment]
Thanks! I think I understand the use-case. PTAL at the WIP PR #207, and let me know if this would address the use-case.

**Comment by JustinBeckwith** [comment]
As time has gone on, I now think this is a bad idea :)
