### ISSUE TITLE
GTS scripts hang / dont progress 

### ISSUE THREAD

**Issue by maylortaylor** [google/gts#877]
I have a NextJS React app and whenever I run the `gts lint` or `gts fix` scripts, the command line will print out the following but never continue. I am using `"gts": "^5.3.0"`
```
> gts lint

version: 20
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

YOUR TYPESCRIPT VERSION: 5.4.5

Please only submit bug reports when using the officially supported version.

=============
```
This command works fine in my other projects on this same computer.  The `gts clean` command does work / remove the build folder.

**Comment by tonycoco** [comment]
We are working to support more versions of TypeScript, but for now the supported ones are:

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

Can you try to install or lock your version to one in that range?

**Comment by tonycoco** [comment]
This is most likely due to a global version that is incompatible with `"eslint": "8.57.0"` installed.

**Comment by 340rahul** [comment]
Any updates on this?
